package bo.com.tigo.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2019-09-11T17:08:14.665-04:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://ws.tigo.com.bo", name = "ManagementMobileServicesPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ManagementMobileServicesPortType {

    @WebMethod(operationName = "EnableDisableAvailableService", action = "EnableDisableAvailableService")
    @RequestWrapper(localName = "EnableDisableAvailableService", targetNamespace = "http://ws.tigo.com.bo", className = "bo.com.tigo.ws.EnableDisableAvailableService")
    @ResponseWrapper(localName = "responseEnableDisableAvailableService", targetNamespace = "http://ws.tigo.com.bo", className = "bo.com.tigo.ws.ResponseEnableDisableAvailableService")
    public void enableDisableAvailableService(
        @WebParam(name = "requestHeader", targetNamespace = "http://ws.tigo.com.bo")
        bo.com.tigo.ws.RequestHeader requestHeader,
        @WebParam(name = "requestBody", targetNamespace = "http://ws.tigo.com.bo")
        bo.com.tigo.ws.RequestBody requestBody,
        @WebParam(mode = WebParam.Mode.OUT, name = "responseHeader", targetNamespace = "http://ws.tigo.com.bo")
        javax.xml.ws.Holder<ResponseHeader> responseHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "responseBody", targetNamespace = "http://ws.tigo.com.bo")
        javax.xml.ws.Holder<ResponseBody> responseBody
    );

    @WebMethod(operationName = "GetAvailableService", action = "GetAvailableService")
    @RequestWrapper(localName = "GetAvailableService", targetNamespace = "http://ws.tigo.com.bo", className = "bo.com.tigo.ws.GetAvailableService")
    @ResponseWrapper(localName = "responseGetAvailableService", targetNamespace = "http://ws.tigo.com.bo", className = "bo.com.tigo.ws.ResponseGetAvailableService")
    public void getAvailableService(
        @WebParam(name = "requestHeader", targetNamespace = "http://ws.tigo.com.bo")
        bo.com.tigo.ws.RequestHeader requestHeader,
        @WebParam(name = "requestBody", targetNamespace = "http://ws.tigo.com.bo")
        bo.com.tigo.ws.RequesBody requestBody,
        @WebParam(mode = WebParam.Mode.OUT, name = "responseHeader", targetNamespace = "http://ws.tigo.com.bo")
        javax.xml.ws.Holder<ResponseHeader> responseHeader,
        @WebParam(mode = WebParam.Mode.OUT, name = "responseBody", targetNamespace = "http://ws.tigo.com.bo")
        javax.xml.ws.Holder<ResponseBody> responseBody
    );
}
