package bo.com.tigo.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2019-09-11T17:08:14.816-04:00
 * Generated source version: 2.7.8
 * 
 */
@WebServiceClient(name = "ManagementMobileServicesPort", 
                  wsdlLocation = "file:/C:/fuentes%20Servicios/QA01/apiMobilServices/src/main/resources/wsdl/mobileServices.wsdl",
                  targetNamespace = "http://ws.tigo.com.bo") 
public class ManagementMobileServicesPort extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.tigo.com.bo", "ManagementMobileServicesPort");
    public final static QName ManagementMobileServicesPort = new QName("http://ws.tigo.com.bo", "ManagementMobileServicesPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/fuentes%20Servicios/QA01/apiMobilServices/src/main/resources/wsdl/mobileServices.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ManagementMobileServicesPort.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/fuentes%20Servicios/QA01/apiMobilServices/src/main/resources/wsdl/mobileServices.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ManagementMobileServicesPort(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ManagementMobileServicesPort(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ManagementMobileServicesPort() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ManagementMobileServicesPort(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ManagementMobileServicesPort(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ManagementMobileServicesPort(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ManagementMobileServicesPortType
     */
    @WebEndpoint(name = "ManagementMobileServicesPort")
    public ManagementMobileServicesPortType getManagementMobileServicesPort() {
        return super.getPort(ManagementMobileServicesPort, ManagementMobileServicesPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ManagementMobileServicesPortType
     */
    @WebEndpoint(name = "ManagementMobileServicesPort")
    public ManagementMobileServicesPortType getManagementMobileServicesPort(WebServiceFeature... features) {
        return super.getPort(ManagementMobileServicesPort, ManagementMobileServicesPortType.class, features);
    }

}
